name: Regenerate WPT certificates
on:
  schedule:
    # Our certificates are good for a few years, but we regenerate them every 6
    # months to be sure.
    - cron: '0 0 1 */6 *'
jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run cert_regen.sh
      # Use a conditional step instead of a conditional job to work around #20700.
      if: github.repository == 'web-platform-tests/wpt'
      run: |
        python wpt regen-certs --force
    - name: Commit and create pull request
      # Use a conditional step instead of a conditional job to work around #20700.
      if: github.repository == 'web-platform-tests/wpt'
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated regeneration of WPT certificates
        title: Regenerate WPT certificates
        body: |
          This automated pull request updates the core WPT certificates.

          Please test the new certs locally before merging this pull request.

          Pull request auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: actions/regen-certs
